name = "JuliaSetCycle"
uuid = "168312d5-c99f-4fd2-bfae-bb59715a612e"
authors = ["David Faden (revfad.com) <dfaden@gmail.com>"]
version = "0.1.1"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
GLMakie = "0.12.0"
